mysql -u root --password="${MARIADB_ROOT_PASSWORD}" -e "
    CREATE USER IF NOT EXISTS '${XI_SQL_USERNAME}'@'%' IDENTIFIED BY '${XI_SQL_PASSWORD}';
    CREATE DATABASE IF NOT EXISTS ${XI_SQL_DATABASE};
    USE ${XI_SQL_DATABASE};
    GRANT ALL PRIVILEGES ON ${XI_SQL_DATABASE}.* TO '${XI_SQL_USERNAME}'@'%';"
